/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#pragma once

#include "pr_comp.h"			// defs shared with qcc
#include "progdefs.h"			// generated by program cdefs
#include "cvar.h"
#include "link.h"
#include "mathlib.h"
#include "protocol.h"

typedef union eval_s
{
	string_t		string;
	float			_float;
	float			vector[3];
	func_t			function;
	int				_int;
	int				edict;
} eval_t;	

#define	MAX_ENT_LEAFS	16
typedef struct edict_s
{
	bool	free;
	link_t		area;				// linked to a division node or leaf
	
	int			num_leafs;
	int			leafnums[MAX_ENT_LEAFS];	// visibility bit numbers

	entity_state_t	baseline;
	float		alpha;				// FTE's alpha and colormod map keys, for progs
	vec3_t		colormod;			// without such fields
	
	float		freetime;			// sv.time when the object was freed
	entvars_t	v;					// C exported fields from progs
// other fields from progs come immediately after
} edict_t;
#define	EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l,edict_t,area)

//============================================================================

// the QuakeC virtual machine
typedef struct
{
	dprograms_t		*progs;
	dfunction_t		*functions;
	char			*strings;
	dstatement_t	*statements;
	globalvars_t	*global_struct;
	float			*globals;			// same as global_struct
	int				edict_size;			// in bytes

	bool			trace;
	dfunction_t		*xfunction;			// the function running
	int				argc;				// arguments of the builtin being called
	int				num_prstr;			// C strings QuakeC can reach

	// optional QuakeC fields, as offsets into an edict's fields; 0 without
	int				fofs_alpha;			// float
	int				fofs_colormod;		// vector

	// optional QuakeC functions
	func_t			SpectatorConnect;
	func_t			SpectatorThink;
	func_t			SpectatorDisconnect;
} pr_state_t;

extern	pr_state_t	pr;


//============================================================================

void PR_Init (void);
void PR_ResetStack (void);	// after an error left functions running

void PR_ExecuteProgram (func_t fnum);
void PR_LoadProgs (void);

void PR_Profile_f (void);

edict_t *ED_Alloc (void);
void ED_Free (edict_t *ed);

char	*ED_NewString (char *string);
// returns a copy of the string allocated from the server's string heap

void ED_Print (edict_t *ed);
char *ED_ParseEdict (char *data, edict_t *ent);


void ED_LoadFromFile (char *data);


edict_t *EDICT_NUM(int n);
int NUM_FOR_EDICT(edict_t *e);

#define	NEXT_EDICT(e) ((edict_t *)( (byte *)e + pr.edict_size))

#define	EDICT_TO_PROG(e) ((int)((byte *)(e) - (byte *)sv.edicts))
#define PROG_TO_EDICT(e) ((edict_t *)((byte *)sv.edicts + e))

//============================================================================

#define	G_FLOAT(o) (pr.globals[o])
#define	G_INT(o) (*(int *)&pr.globals[o])
#define	G_EDICT(o) ((edict_t *)((byte *)sv.edicts+ *(int *)&pr.globals[o]))
#define G_EDICTNUM(o) NUM_FOR_EDICT(G_EDICT(o))
#define	G_VECTOR(o) (&pr.globals[o])
#define	G_STRING(o) (PR_GetString(*(string_t *)&pr.globals[o]))
#define	G_FUNCTION(o) (*(func_t *)&pr.globals[o])

#define	E_FLOAT(e,o) (((float*)&e->v)[o])
#define	E_INT(e,o) (*(int *)&((float*)&e->v)[o])
#define	E_VECTOR(e,o) (&((float*)&e->v)[o])
#define	E_STRING(e,o) (PR_GetString(*(string_t *)&((float*)&e->v)[o]))


typedef void (*builtin_t) (void);
extern	builtin_t *pr_builtins;
extern int pr_numbuiltins;




[[noreturn]] void PR_RunError (char *error, ...);

void ED_PrintEdicts (void);
void ED_PrintNum (int ent);

eval_t *GetEdictFieldValue(edict_t *ed, char *field);

//
// PR STrings stuff
//
#define MAX_PRSTR 1024


char *PR_GetString(int num);
int PR_SetString(char *s);
