# Instruction-set target. Selects compiler flags, the SIMD kernel backend and the
# startup CPU check implementation.
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64|ARM64)$" OR CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
	set(SW_ARCH_ARM64 ON)
	set(SW_ARCH_DEFAULT "generic")
else()
	set(SW_ARCH_ARM64 OFF)
	set(SW_ARCH_DEFAULT "x86-64-v4")
endif()
set(SW_ARCH "${SW_ARCH_DEFAULT}" CACHE STRING "Target instruction set (x86-64-v4, apple-m3 or generic)")
set_property(CACHE SW_ARCH PROPERTY STRINGS x86-64-v4 apple-m3 generic)

if(SW_ARCH STREQUAL "x86-64-v4")
	if(SW_ARCH_ARM64)
		message(FATAL_ERROR "SW_ARCH x86-64-v4 needs an x86-64 target")
	endif()
	set(SW_ARCH_SUFFIX x86_64_v4)
	if(CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC" AND CMAKE_C_COMPILER_ID STREQUAL "Clang")
		set(SW_ARCH_FLAGS "/clang:-march=x86-64-v4")
	else()
		set(SW_ARCH_FLAGS "/arch:AVX512")
	endif()
elseif(SW_ARCH STREQUAL "apple-m3")
	# the M2's instruction set, scheduled for the M3; NEON kernels
	if(NOT SW_ARCH_ARM64)
		message(FATAL_ERROR "SW_ARCH apple-m3 needs an arm64 target")
	endif()
	set(SW_ARCH_SUFFIX apple_m3)
	set(SW_ARCH_FLAGS "-mcpu=apple-m3")
elseif(SW_ARCH STREQUAL "generic")
	set(SW_ARCH_SUFFIX generic)
	set(SW_ARCH_FLAGS "")
else()
	message(FATAL_ERROR "Unknown SW_ARCH '${SW_ARCH}'")
endif()

# Applies the architecture flags to a target. Entry/CPU-check code must not use this.
function(sw_set_arch target)
	if(SW_ARCH_FLAGS)
		target_compile_options(${target} PRIVATE ${SW_ARCH_FLAGS})
	endif()
endfunction()

# the spin-wait hint of the target's architecture (cpu/<arch>/cpu_relax.h)
if(SW_ARCH_ARM64)
	set(SW_CPU_RELAX_DIR "${PROJECT_SOURCE_DIR}/src/platform/cpu/arm64")
else()
	set(SW_CPU_RELAX_DIR "${PROJECT_SOURCE_DIR}/src/platform/cpu/x86_64")
endif()
